name: Release

on:
  workflow_run:
    workflows:
      - "Test"
    branches:
      - master
    types:
      - completed

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: npm install

      - uses: cycjimmy/semantic-release-action@master
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/npm
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
